-- O VÍNCULO - RESET LIMPO DO BANCO
-- Use em desenvolvimento/TCC quando você puder apagar os dados atuais.
-- Supabase > SQL Editor > New query > cole tudo > Run.
--
-- IMPORTANTE:
-- 1) Isso apaga as tabelas públicas do projeto, mas NÃO apaga usuários do Authentication.
-- 2) Depois de rodar, as contas já existentes no Auth ganham linha em perfis.
-- 3) Contas com tipo_usuario='psicologo' ganham linha em psicologos automaticamente.

create extension if not exists pgcrypto;

drop table if exists public.mensagens cascade;
drop table if exists public.avaliacoes cascade;
drop table if exists public.favoritos cascade;
drop table if exists public.agendamentos cascade;
drop table if exists public.bloqueios_agenda cascade;
drop table if exists public.disponibilidades cascade;
drop table if exists public.recomendacoes cascade;
drop table if exists public.triagens cascade;
drop table if exists public.psicologo_especialidades cascade;
drop table if exists public.especialidades cascade;
drop table if exists public.assinaturas cascade;
drop table if exists public.planos cascade;
drop table if exists public.psicologos cascade;
drop table if exists public.perfis cascade;

drop function if exists public.criar_perfil_novo_usuario() cascade;
drop function if exists public.garantir_meu_perfil() cascade;
drop function if exists public.criar_agendamento(uuid,text) cascade;
drop function if exists public.sincronizar_disponibilidade_agendamento() cascade;

create table public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  tipo_usuario text not null default 'cliente'
    check (tipo_usuario in ('cliente', 'psicologo')),
  foto_url text,
  telefone text,
  data_nascimento date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.psicologos (
  id uuid primary key default gen_random_uuid(),
  perfil_id uuid not null unique references public.perfis(id) on delete cascade,
  crp text not null,
  estado_crp text not null,
  biografia text,
  modalidade text not null default 'online'
    check (modalidade in ('online', 'presencial', 'ambos')),
  valor_consulta numeric(10,2) not null default 0
    check (valor_consulta >= 0),
  anos_experiencia integer not null default 0
    check (anos_experiencia >= 0),
  perfil_ativo boolean not null default true,
  verificado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.especialidades (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  created_at timestamptz not null default now()
);

create table public.psicologo_especialidades (
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  especialidade_id bigint not null references public.especialidades(id) on delete cascade,
  primary key (psicologo_id, especialidade_id)
);

create table public.triagens (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.perfis(id) on delete cascade,
  respostas jsonb not null default '{}'::jsonb,
  concluida boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.recomendacoes (
  id uuid primary key default gen_random_uuid(),
  triagem_id uuid not null references public.triagens(id) on delete cascade,
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  compatibilidade integer not null check (compatibilidade between 0 and 100),
  created_at timestamptz not null default now(),
  unique (triagem_id, psicologo_id)
);

create table public.disponibilidades (
  id uuid primary key default gen_random_uuid(),
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  data date not null,
  hora_inicio time not null,
  hora_fim time not null,
  status text not null default 'disponivel'
    check (status in ('disponivel', 'reservado', 'bloqueado')),
  created_at timestamptz not null default now(),
  check (hora_fim > hora_inicio),
  unique (psicologo_id, data, hora_inicio)
);

create table public.agendamentos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.perfis(id) on delete cascade,
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  disponibilidade_id uuid references public.disponibilidades(id) on delete set null,
  data_consulta date not null,
  hora_inicio time not null,
  hora_fim time not null,
  modalidade text not null check (modalidade in ('online', 'presencial')),
  valor numeric(10,2) not null check (valor >= 0),
  status text not null default 'pendente'
    check (status in ('pendente', 'confirmado', 'concluido', 'cancelado')),
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (hora_fim > hora_inicio)
);

create table public.favoritos (
  cliente_id uuid not null references public.perfis(id) on delete cascade,
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (cliente_id, psicologo_id)
);

create table public.avaliacoes (
  id uuid primary key default gen_random_uuid(),
  agendamento_id uuid not null unique references public.agendamentos(id) on delete cascade,
  cliente_id uuid not null references public.perfis(id) on delete cascade,
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  nota integer not null check (nota between 1 and 5),
  comentario text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.mensagens (
  id uuid primary key default gen_random_uuid(),
  remetente_id uuid not null references public.perfis(id) on delete cascade,
  destinatario_id uuid not null references public.perfis(id) on delete cascade,
  conteudo text not null check (char_length(conteudo) between 1 and 5000),
  lida_em timestamptz,
  created_at timestamptz not null default now(),
  check (remetente_id <> destinatario_id)
);

create table public.planos (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  preco numeric(10,2) not null default 0 check (preco >= 0),
  recursos jsonb not null default '[]'::jsonb,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.assinaturas (
  id uuid primary key default gen_random_uuid(),
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  plano_id bigint not null references public.planos(id),
  status text not null default 'ativa'
    check (status in ('ativa', 'cancelada', 'atrasada', 'expirada')),
  data_inicio date not null default current_date,
  data_renovacao date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.especialidades(nome) values
  ('Ansiedade'),('Depressão'),('Relacionamentos'),('Autoestima'),
  ('TDAH'),('Luto'),('Burnout'),('Traumas')
on conflict (nome) do nothing;

insert into public.planos(nome,preco,recursos) values
  ('Essencial', 0, '["Perfil profissional", "Agenda básica", "Até 5 solicitações/mês"]'::jsonb),
  ('Profissional', 59, '["Solicitações ilimitadas", "Destaque na busca", "Gestão de disponibilidade", "Relatórios"]'::jsonb),
  ('Clínica', 129, '["Tudo do Profissional", "Suporte prioritário", "Página personalizada", "Recursos avançados"]'::jsonb)
on conflict (nome) do nothing;

create or replace function public.criar_perfil_novo_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  novo_psicologo_id uuid;
begin
  insert into public.perfis (id, nome, tipo_usuario)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'nome',''), split_part(new.email, '@', 1), 'Usuário'),
    case when new.raw_user_meta_data ->> 'tipo_usuario' = 'psicologo' then 'psicologo' else 'cliente' end
  )
  on conflict (id) do update set
    nome = excluded.nome,
    tipo_usuario = excluded.tipo_usuario;

  if new.raw_user_meta_data ->> 'tipo_usuario' = 'psicologo' then
    insert into public.psicologos (
      perfil_id, crp, estado_crp, biografia, modalidade, valor_consulta, perfil_ativo
    ) values (
      new.id,
      coalesce(nullif(new.raw_user_meta_data ->> 'crp',''), 'CRP pendente'),
      coalesce(nullif(new.raw_user_meta_data ->> 'estado_crp',''), 'Não informado'),
      coalesce(new.raw_user_meta_data ->> 'biografia', ''),
      coalesce(new.raw_user_meta_data ->> 'modalidade', 'online'),
      coalesce((nullif(new.raw_user_meta_data ->> 'valor_consulta',''))::numeric, 0),
      true
    )
    on conflict (perfil_id) do update set
      crp = excluded.crp,
      estado_crp = excluded.estado_crp,
      biografia = excluded.biografia,
      modalidade = excluded.modalidade,
      valor_consulta = excluded.valor_consulta,
      perfil_ativo = true
    returning id into novo_psicologo_id;

    insert into public.psicologo_especialidades (psicologo_id, especialidade_id)
    select novo_psicologo_id, e.id
    from public.especialidades e
    where e.nome in (
      select jsonb_array_elements_text(coalesce(new.raw_user_meta_data -> 'especialidades', '[]'::jsonb))
    )
    on conflict do nothing;
  end if;

  return new;
end;
$$;

create trigger criar_perfil_apos_signup
after insert on auth.users
for each row execute procedure public.criar_perfil_novo_usuario();

create or replace function public.garantir_meu_perfil()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  usuario auth.users%rowtype;
  novo_psicologo_id uuid;
begin
  select * into usuario from auth.users where id = auth.uid();
  if usuario.id is null then
    raise exception 'Usuário não autenticado.';
  end if;

  insert into public.perfis(id,nome,tipo_usuario)
  values (
    usuario.id,
    coalesce(nullif(usuario.raw_user_meta_data->>'nome',''), split_part(usuario.email,'@',1), 'Usuário'),
    case when usuario.raw_user_meta_data->>'tipo_usuario'='psicologo' then 'psicologo' else 'cliente' end
  )
  on conflict(id) do update set
    nome = coalesce(public.perfis.nome, excluded.nome),
    tipo_usuario = excluded.tipo_usuario;

  if usuario.raw_user_meta_data->>'tipo_usuario'='psicologo' then
    insert into public.psicologos(perfil_id,crp,estado_crp,biografia,modalidade,valor_consulta,perfil_ativo)
    values (
      usuario.id,
      coalesce(nullif(usuario.raw_user_meta_data->>'crp',''), 'CRP pendente'),
      coalesce(nullif(usuario.raw_user_meta_data->>'estado_crp',''), 'Não informado'),
      coalesce(usuario.raw_user_meta_data->>'biografia',''),
      coalesce(usuario.raw_user_meta_data->>'modalidade','online'),
      coalesce((nullif(usuario.raw_user_meta_data->>'valor_consulta',''))::numeric,0),
      true
    )
    on conflict(perfil_id) do update set perfil_ativo = true
    returning id into novo_psicologo_id;
  end if;
end;
$$;

grant execute on function public.garantir_meu_perfil() to authenticated;

create or replace function public.criar_agendamento(p_disponibilidade_id uuid, p_modalidade text default 'online')
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cliente uuid := auth.uid();
  v_slot public.disponibilidades%rowtype;
  v_psicologo public.psicologos%rowtype;
  v_id uuid;
begin
  if v_cliente is null then raise exception 'Usuário não autenticado.'; end if;

  select * into v_slot
  from public.disponibilidades
  where id = p_disponibilidade_id
  for update;

  if not found or v_slot.status <> 'disponivel' then
    raise exception 'Horário indisponível.';
  end if;

  select * into v_psicologo
  from public.psicologos
  where id = v_slot.psicologo_id and perfil_ativo = true;

  if not found then raise exception 'Psicólogo indisponível.'; end if;

  insert into public.agendamentos(
    cliente_id, psicologo_id, disponibilidade_id, data_consulta,
    hora_inicio, hora_fim, modalidade, valor, status
  )
  values (
    v_cliente, v_psicologo.id, v_slot.id, v_slot.data,
    v_slot.hora_inicio, v_slot.hora_fim,
    case when p_modalidade = 'presencial' then 'presencial' else 'online' end,
    v_psicologo.valor_consulta, 'pendente'
  )
  returning id into v_id;

  update public.disponibilidades set status='reservado' where id=v_slot.id;
  return v_id;
end;
$$;

grant execute on function public.criar_agendamento(uuid,text) to authenticated;

create or replace function public.sincronizar_disponibilidade_agendamento()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.disponibilidade_id is not null and new.status='cancelado' and old.status <> 'cancelado' then
    update public.disponibilidades set status='disponivel' where id=new.disponibilidade_id;
  end if;
  return new;
end;
$$;

create trigger sincronizar_disponibilidade_apos_agendamento
after update of status on public.agendamentos
for each row execute procedure public.sincronizar_disponibilidade_agendamento();

alter table public.perfis enable row level security;
alter table public.psicologos enable row level security;
alter table public.especialidades enable row level security;
alter table public.psicologo_especialidades enable row level security;
alter table public.triagens enable row level security;
alter table public.recomendacoes enable row level security;
alter table public.disponibilidades enable row level security;
alter table public.agendamentos enable row level security;
alter table public.favoritos enable row level security;
alter table public.avaliacoes enable row level security;
alter table public.mensagens enable row level security;
alter table public.planos enable row level security;
alter table public.assinaturas enable row level security;

create policy "Perfis visiveis"
on public.perfis for select to authenticated
using (
  id = auth.uid()
  or exists (select 1 from public.psicologos p where p.perfil_id = perfis.id and p.perfil_ativo = true)
);

create policy "Usuario atualiza proprio perfil"
on public.perfis for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "Psicologos visiveis"
on public.psicologos for select to authenticated
using (perfil_ativo = true or perfil_id = auth.uid());

create policy "Psicologo cria proprio perfil"
on public.psicologos for insert to authenticated
with check (perfil_id = auth.uid());

create policy "Psicologo atualiza proprio perfil"
on public.psicologos for update to authenticated
using (perfil_id = auth.uid())
with check (perfil_id = auth.uid());

create policy "Especialidades visiveis"
on public.especialidades for select to authenticated using (true);

create policy "Especialidades dos psicologos visiveis"
on public.psicologo_especialidades for select to authenticated using (true);

create policy "Psicologo gerencia especialidades"
on public.psicologo_especialidades for all to authenticated
using (exists(select 1 from public.psicologos p where p.id = psicologo_id and p.perfil_id = auth.uid()))
with check (exists(select 1 from public.psicologos p where p.id = psicologo_id and p.perfil_id = auth.uid()));

create policy "Cliente gerencia triagens"
on public.triagens for all to authenticated
using (cliente_id = auth.uid())
with check (cliente_id = auth.uid());

create policy "Cliente acessa recomendacoes"
on public.recomendacoes for all to authenticated
using (exists(select 1 from public.triagens t where t.id = triagem_id and t.cliente_id = auth.uid()))
with check (exists(select 1 from public.triagens t where t.id = triagem_id and t.cliente_id = auth.uid()));

create policy "Disponibilidades visiveis"
on public.disponibilidades for select to authenticated
using (
  status = 'disponivel'
  or exists(select 1 from public.psicologos p where p.id = psicologo_id and p.perfil_id = auth.uid())
);

create policy "Psicologo gerencia disponibilidade"
on public.disponibilidades for all to authenticated
using (exists(select 1 from public.psicologos p where p.id = psicologo_id and p.perfil_id = auth.uid()))
with check (exists(select 1 from public.psicologos p where p.id = psicologo_id and p.perfil_id = auth.uid()));

create policy "Agendamentos relacionados"
on public.agendamentos for select to authenticated
using (
  cliente_id = auth.uid()
  or exists(select 1 from public.psicologos p where p.id = psicologo_id and p.perfil_id = auth.uid())
);

create policy "Cliente cria agendamento"
on public.agendamentos for insert to authenticated
with check (cliente_id = auth.uid());

create policy "Participantes atualizam agendamento"
on public.agendamentos for update to authenticated
using (
  cliente_id = auth.uid()
  or exists(select 1 from public.psicologos p where p.id = psicologo_id and p.perfil_id = auth.uid())
);

create policy "Favoritos do cliente"
on public.favoritos for all to authenticated
using (cliente_id = auth.uid())
with check (cliente_id = auth.uid());

create policy "Avaliacoes visiveis"
on public.avaliacoes for select to authenticated using (true);

create policy "Cliente cria avaliacao propria"
on public.avaliacoes for insert to authenticated
with check (cliente_id = auth.uid());

create policy "Mensagens relacionadas"
on public.mensagens for all to authenticated
using (remetente_id = auth.uid() or destinatario_id = auth.uid())
with check (remetente_id = auth.uid());

create policy "Planos visiveis"
on public.planos for select to authenticated using (ativo = true);

create policy "Assinaturas do psicologo"
on public.assinaturas for select to authenticated
using (exists(select 1 from public.psicologos p where p.id = psicologo_id and p.perfil_id = auth.uid()));

insert into public.perfis(id,nome,tipo_usuario,foto_url)
select
  u.id,
  coalesce(nullif(u.raw_user_meta_data->>'nome',''), split_part(u.email,'@',1), 'Usuário'),
  case when u.raw_user_meta_data->>'tipo_usuario'='psicologo' then 'psicologo' else 'cliente' end,
  nullif(u.raw_user_meta_data->>'foto_url','')
from auth.users u
on conflict(id) do update set
  nome = excluded.nome,
  tipo_usuario = excluded.tipo_usuario;

insert into public.psicologos(perfil_id,crp,estado_crp,biografia,modalidade,valor_consulta,perfil_ativo)
select
  u.id,
  coalesce(nullif(u.raw_user_meta_data->>'crp',''), 'CRP pendente'),
  coalesce(nullif(u.raw_user_meta_data->>'estado_crp',''), 'Não informado'),
  coalesce(u.raw_user_meta_data->>'biografia',''),
  coalesce(u.raw_user_meta_data->>'modalidade','online'),
  coalesce((nullif(u.raw_user_meta_data->>'valor_consulta',''))::numeric,0),
  true
from auth.users u
where u.raw_user_meta_data->>'tipo_usuario'='psicologo'
on conflict(perfil_id) do update set perfil_ativo = true;
