-- O VÍNCULO - SCHEMA COMPLETO PARA SUPABASE
-- Execute este arquivo uma única vez em: Supabase > SQL Editor > New query > Run

create extension if not exists pgcrypto;

-- =========================================================
-- TABELAS
-- =========================================================

create table public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  tipo_usuario text not null default 'cliente'
    check (tipo_usuario in ('cliente', 'psicologo')),
  foto_url text,
  telefone text,
  data_nascimento date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.psicologos (
  id uuid primary key default gen_random_uuid(),
  perfil_id uuid not null unique references public.perfis(id) on delete cascade,
  crp text not null unique,
  estado_crp text not null,
  biografia text,
  modalidade text not null default 'online'
    check (modalidade in ('online', 'presencial', 'ambos')),
  valor_consulta numeric(10,2) not null default 0
    check (valor_consulta >= 0),
  anos_experiencia integer not null default 0
    check (anos_experiencia >= 0),
  perfil_ativo boolean not null default true,
  verificado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.especialidades (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  created_at timestamptz not null default now()
);

create table public.psicologo_especialidades (
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  especialidade_id bigint not null references public.especialidades(id) on delete cascade,
  primary key (psicologo_id, especialidade_id)
);

create table public.triagens (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.perfis(id) on delete cascade,
  respostas jsonb not null default '{}'::jsonb,
  concluida boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.recomendacoes (
  id uuid primary key default gen_random_uuid(),
  triagem_id uuid not null references public.triagens(id) on delete cascade,
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  compatibilidade integer not null
    check (compatibilidade between 0 and 100),
  created_at timestamptz not null default now(),
  unique (triagem_id, psicologo_id)
);

create table public.disponibilidades (
  id uuid primary key default gen_random_uuid(),
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  data date not null,
  hora_inicio time not null,
  hora_fim time not null,
  status text not null default 'disponivel'
    check (status in ('disponivel', 'reservado', 'bloqueado')),
  created_at timestamptz not null default now(),
  check (hora_fim > hora_inicio),
  unique (psicologo_id, data, hora_inicio)
);

create table public.bloqueios_agenda (
  id uuid primary key default gen_random_uuid(),
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  data_inicio date not null,
  data_fim date not null,
  motivo text,
  created_at timestamptz not null default now(),
  check (data_fim >= data_inicio)
);

create table public.agendamentos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.perfis(id) on delete cascade,
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  disponibilidade_id uuid references public.disponibilidades(id) on delete set null,
  data_consulta date not null,
  hora_inicio time not null,
  hora_fim time not null,
  modalidade text not null
    check (modalidade in ('online', 'presencial')),
  valor numeric(10,2) not null check (valor >= 0),
  status text not null default 'pendente'
    check (status in ('pendente', 'confirmado', 'concluido', 'cancelado')),
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (hora_fim > hora_inicio)
);

create table public.favoritos (
  cliente_id uuid not null references public.perfis(id) on delete cascade,
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (cliente_id, psicologo_id)
);

create table public.avaliacoes (
  id uuid primary key default gen_random_uuid(),
  agendamento_id uuid not null unique references public.agendamentos(id) on delete cascade,
  cliente_id uuid not null references public.perfis(id) on delete cascade,
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  nota integer not null check (nota between 1 and 5),
  comentario text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.mensagens (
  id uuid primary key default gen_random_uuid(),
  remetente_id uuid not null references public.perfis(id) on delete cascade,
  destinatario_id uuid not null references public.perfis(id) on delete cascade,
  conteudo text not null check (char_length(conteudo) between 1 and 5000),
  lida_em timestamptz,
  created_at timestamptz not null default now(),
  check (remetente_id <> destinatario_id)
);

create table public.planos (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  preco numeric(10,2) not null default 0 check (preco >= 0),
  recursos jsonb not null default '[]'::jsonb,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.assinaturas (
  id uuid primary key default gen_random_uuid(),
  psicologo_id uuid not null references public.psicologos(id) on delete cascade,
  plano_id bigint not null references public.planos(id),
  status text not null default 'ativa'
    check (status in ('ativa', 'cancelada', 'atrasada', 'expirada')),
  data_inicio date not null default current_date,
  data_renovacao date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- ÍNDICES
-- =========================================================

create index psicologos_perfil_ativo_idx
  on public.psicologos (perfil_ativo);
create index psicologo_especialidades_especialidade_idx
  on public.psicologo_especialidades (especialidade_id);
create index triagens_cliente_idx
  on public.triagens (cliente_id, created_at desc);
create index recomendacoes_triagem_idx
  on public.recomendacoes (triagem_id, compatibilidade desc);
create index disponibilidades_busca_idx
  on public.disponibilidades (psicologo_id, data, status);
create index agendamentos_cliente_idx
  on public.agendamentos (cliente_id, data_consulta);
create index agendamentos_psicologo_idx
  on public.agendamentos (psicologo_id, data_consulta);
create index avaliacoes_psicologo_idx
  on public.avaliacoes (psicologo_id, created_at desc);
create index mensagens_conversa_idx
  on public.mensagens (remetente_id, destinatario_id, created_at);
create index assinaturas_psicologo_idx
  on public.assinaturas (psicologo_id, status);

-- =========================================================
-- PERFIL AUTOMÁTICO APÓS CADASTRO NO SUPABASE AUTH
-- =========================================================

create or replace function public.criar_perfil_novo_usuario()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  novo_psicologo_id uuid;
begin
  insert into public.perfis (id, nome, tipo_usuario)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nome', split_part(new.email, '@', 1)),
    case
      when new.raw_user_meta_data ->> 'tipo_usuario' = 'psicologo' then 'psicologo'
      else 'cliente'
    end
  );

  if new.raw_user_meta_data ->> 'tipo_usuario' = 'psicologo' then
    insert into public.psicologos (
      perfil_id,
      crp,
      estado_crp,
      biografia,
      modalidade,
      valor_consulta,
      perfil_ativo
    ) values (
      new.id,
      new.raw_user_meta_data ->> 'crp',
      new.raw_user_meta_data ->> 'estado_crp',
      new.raw_user_meta_data ->> 'biografia',
      coalesce(new.raw_user_meta_data ->> 'modalidade', 'online'),
      coalesce((new.raw_user_meta_data ->> 'valor_consulta')::numeric, 0),
      true
    )
    returning id into novo_psicologo_id;

    insert into public.psicologo_especialidades (psicologo_id, especialidade_id)
    select novo_psicologo_id, e.id
    from public.especialidades e
    where e.nome in (
      select jsonb_array_elements_text(
        coalesce(new.raw_user_meta_data -> 'especialidades', '[]'::jsonb)
      )
    );
  end if;

  return new;
end;
$$;

create trigger criar_perfil_apos_cadastro
  after insert on auth.users
  for each row execute procedure public.criar_perfil_novo_usuario();

create or replace function public.garantir_meu_perfil()
returns void language plpgsql security definer set search_path='' as $$
begin
  insert into public.perfis(id,nome,tipo_usuario)
  select u.id,
    coalesce(nullif(u.raw_user_meta_data->>'nome',''),split_part(u.email,'@',1),'Usuário'),
    case when u.raw_user_meta_data->>'tipo_usuario'='psicologo' then 'psicologo' else 'cliente' end
  from auth.users u where u.id=auth.uid()
  on conflict(id) do nothing;
end; $$;

create or replace function public.atualizar_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger perfis_updated_at
  before update on public.perfis
  for each row execute procedure public.atualizar_updated_at();
create trigger psicologos_updated_at
  before update on public.psicologos
  for each row execute procedure public.atualizar_updated_at();
create trigger agendamentos_updated_at
  before update on public.agendamentos
  for each row execute procedure public.atualizar_updated_at();
create trigger avaliacoes_updated_at
  before update on public.avaliacoes
  for each row execute procedure public.atualizar_updated_at();
create trigger assinaturas_updated_at
  before update on public.assinaturas
  for each row execute procedure public.atualizar_updated_at();

-- Reserva o horário e cria o agendamento em uma única transação segura.
create or replace function public.criar_agendamento(p_disponibilidade_id uuid, p_modalidade text default 'online')
returns uuid language plpgsql security definer set search_path = public, auth as $$
declare v_cliente uuid:=auth.uid(); v_slot public.disponibilidades%rowtype; v_psicologo public.psicologos%rowtype; v_id uuid;
begin
  if v_cliente is null then raise exception 'Faça login para agendar.'; end if;
  if not exists(select 1 from public.perfis where id=v_cliente and tipo_usuario='cliente') then raise exception 'Somente clientes podem agendar.'; end if;
  if p_modalidade not in ('online','presencial') then raise exception 'Modalidade inválida.'; end if;
  select * into v_slot from public.disponibilidades where id=p_disponibilidade_id for update;
  if not found or v_slot.status<>'disponivel' then raise exception 'Este horário não está mais disponível.'; end if;
  if v_slot.data<current_date then raise exception 'Não é possível agendar uma data passada.'; end if;
  select * into v_psicologo from public.psicologos where id=v_slot.psicologo_id and perfil_ativo=true;
  if not found then raise exception 'O perfil profissional não está ativo.'; end if;
  if v_psicologo.modalidade<>'ambos' and v_psicologo.modalidade<>p_modalidade then raise exception 'Modalidade não oferecida.'; end if;
  insert into public.agendamentos(cliente_id,psicologo_id,disponibilidade_id,data_consulta,hora_inicio,hora_fim,modalidade,valor,status)
  values(v_cliente,v_slot.psicologo_id,v_slot.id,v_slot.data,v_slot.hora_inicio,v_slot.hora_fim,p_modalidade,v_psicologo.valor_consulta,'pendente') returning id into v_id;
  update public.disponibilidades set status='reservado' where id=v_slot.id; return v_id;
end; $$;

create or replace function public.sincronizar_disponibilidade_agendamento()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.disponibilidade_id is not null and new.status='cancelado' and old.status<>'cancelado' then update public.disponibilidades set status='disponivel' where id=new.disponibilidade_id; end if;
  return new;
end; $$;
create trigger sincronizar_disponibilidade_apos_agendamento after update of status on public.agendamentos for each row execute procedure public.sincronizar_disponibilidade_agendamento();

-- =========================================================
-- ROW LEVEL SECURITY (RLS)
-- =========================================================

alter table public.perfis enable row level security;
alter table public.psicologos enable row level security;
alter table public.especialidades enable row level security;
alter table public.psicologo_especialidades enable row level security;
alter table public.triagens enable row level security;
alter table public.recomendacoes enable row level security;
alter table public.disponibilidades enable row level security;
alter table public.bloqueios_agenda enable row level security;
alter table public.agendamentos enable row level security;
alter table public.favoritos enable row level security;
alter table public.avaliacoes enable row level security;
alter table public.mensagens enable row level security;
alter table public.planos enable row level security;
alter table public.assinaturas enable row level security;

-- PERFIS
create policy "Usuário visualiza o próprio perfil e perfis profissionais"
on public.perfis for select to authenticated
using (
  id = (select auth.uid())
  or exists (
    select 1 from public.psicologos p
    where p.perfil_id = perfis.id and p.perfil_ativo = true
  )
);

create policy "Usuário atualiza o próprio perfil"
on public.perfis for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy "Participantes visualizam perfis relacionados"
on public.perfis for select to authenticated using (
  exists(select 1 from public.agendamentos a join public.psicologos ps on ps.id=a.psicologo_id where (a.cliente_id=perfis.id and ps.perfil_id=(select auth.uid())) or (ps.perfil_id=perfis.id and a.cliente_id=(select auth.uid())))
  or exists(select 1 from public.mensagens m where (m.remetente_id=(select auth.uid()) and m.destinatario_id=perfis.id) or (m.destinatario_id=(select auth.uid()) and m.remetente_id=perfis.id))
);

-- PSICÓLOGOS
create policy "Usuários visualizam psicólogos ativos"
on public.psicologos for select to authenticated
using (perfil_ativo = true or perfil_id = (select auth.uid()));

create policy "Psicólogo cria o próprio perfil profissional"
on public.psicologos for insert to authenticated
with check (perfil_id = (select auth.uid()));

create policy "Psicólogo atualiza o próprio perfil profissional"
on public.psicologos for update to authenticated
using (perfil_id = (select auth.uid()))
with check (perfil_id = (select auth.uid()));

create policy "Psicólogo exclui o próprio perfil profissional"
on public.psicologos for delete to authenticated
using (perfil_id = (select auth.uid()));

-- ESPECIALIDADES
create policy "Usuários visualizam especialidades"
on public.especialidades for select to authenticated
using (true);

create policy "Usuários visualizam especialidades dos psicólogos"
on public.psicologo_especialidades for select to authenticated
using (true);

create policy "Psicólogo gerencia as próprias especialidades"
on public.psicologo_especialidades for all to authenticated
using (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

-- TRIAGENS E RECOMENDAÇÕES
create policy "Cliente gerencia as próprias triagens"
on public.triagens for all to authenticated
using (cliente_id = (select auth.uid()))
with check (cliente_id = (select auth.uid()));

create policy "Cliente acessa recomendações da própria triagem"
on public.recomendacoes for all to authenticated
using (
  exists (
    select 1 from public.triagens t
    where t.id = triagem_id and t.cliente_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.triagens t
    where t.id = triagem_id and t.cliente_id = (select auth.uid())
  )
);

-- DISPONIBILIDADE E BLOQUEIOS
create policy "Usuários visualizam horários disponíveis"
on public.disponibilidades for select to authenticated
using (
  status = 'disponivel'
  or exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

create policy "Psicólogo gerencia a própria disponibilidade"
on public.disponibilidades for all to authenticated
using (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

create policy "Psicólogo gerencia os próprios bloqueios"
on public.bloqueios_agenda for all to authenticated
using (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

-- AGENDAMENTOS
create policy "Participantes visualizam seus agendamentos"
on public.agendamentos for select to authenticated
using (
  cliente_id = (select auth.uid())
  or exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

create policy "Cliente cria o próprio agendamento"
on public.agendamentos for insert to authenticated
with check (cliente_id = (select auth.uid()));

create policy "Participantes atualizam seus agendamentos"
on public.agendamentos for update to authenticated
using (
  cliente_id = (select auth.uid())
  or exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
)
with check (
  cliente_id = (select auth.uid())
  or exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

-- FAVORITOS
create policy "Cliente gerencia os próprios favoritos"
on public.favoritos for all to authenticated
using (cliente_id = (select auth.uid()))
with check (cliente_id = (select auth.uid()));

-- AVALIAÇÕES
create policy "Usuários visualizam avaliações"
on public.avaliacoes for select to authenticated
using (true);

create policy "Cliente avalia consulta concluída"
on public.avaliacoes for insert to authenticated
with check (
  cliente_id = (select auth.uid())
  and exists (
    select 1 from public.agendamentos a
    where a.id = agendamento_id
      and a.cliente_id = (select auth.uid())
      and a.psicologo_id = avaliacoes.psicologo_id
      and a.status = 'concluido'
  )
);

create policy "Cliente atualiza a própria avaliação"
on public.avaliacoes for update to authenticated
using (cliente_id = (select auth.uid()))
with check (cliente_id = (select auth.uid()));

create policy "Cliente exclui a própria avaliação"
on public.avaliacoes for delete to authenticated
using (cliente_id = (select auth.uid()));

-- MENSAGENS
create policy "Participantes visualizam suas mensagens"
on public.mensagens for select to authenticated
using (
  remetente_id = (select auth.uid())
  or destinatario_id = (select auth.uid())
);

create policy "Usuário envia mensagem em seu nome"
on public.mensagens for insert to authenticated
with check (remetente_id = (select auth.uid()));

create policy "Destinatário marca mensagem como lida"
on public.mensagens for update to authenticated
using (destinatario_id = (select auth.uid()))
with check (destinatario_id = (select auth.uid()));

-- PLANOS E ASSINATURAS
create policy "Usuários visualizam planos ativos"
on public.planos for select to authenticated
using (ativo = true);

create policy "Psicólogo visualiza a própria assinatura"
on public.assinaturas for select to authenticated
using (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

create policy "Psicólogo cria a própria assinatura"
on public.assinaturas for insert to authenticated
with check (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

create policy "Psicólogo atualiza a própria assinatura"
on public.assinaturas for update to authenticated
using (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.psicologos p
    where p.id = psicologo_id and p.perfil_id = (select auth.uid())
  )
);

-- =========================================================
-- PERMISSÕES DA DATA API
-- =========================================================

grant usage on schema public to authenticated;
grant execute on function public.criar_agendamento(uuid,text) to authenticated;
grant execute on function public.garantir_meu_perfil() to authenticated;
grant select, insert, update, delete on table
  public.perfis,
  public.psicologos,
  public.especialidades,
  public.psicologo_especialidades,
  public.triagens,
  public.recomendacoes,
  public.disponibilidades,
  public.bloqueios_agenda,
  public.agendamentos,
  public.favoritos,
  public.avaliacoes,
  public.mensagens,
  public.planos,
  public.assinaturas
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- =========================================================
-- DADOS INICIAIS
-- =========================================================

insert into public.especialidades (nome) values
  ('Ansiedade'),
  ('Depressão'),
  ('Relacionamentos'),
  ('Autoestima'),
  ('TDAH'),
  ('Luto'),
  ('Burnout'),
  ('Traumas'),
  ('Estresse'),
  ('Desenvolvimento pessoal')
on conflict (nome) do nothing;

insert into public.planos (nome, preco, recursos) values
  ('Essencial', 0, '["Perfil profissional", "Agenda básica", "Até 5 solicitações por mês"]'::jsonb),
  ('Profissional', 59, '["Solicitações ilimitadas", "Destaque na busca", "Gestão de disponibilidade", "Relatórios"]'::jsonb),
  ('Clínica', 129, '["Tudo do Profissional", "Suporte prioritário", "Página personalizada", "Recursos avançados"]'::jsonb)
on conflict (nome) do nothing;

-- =========================================================
-- STORAGE PARA FOTOS DE PERFIL
-- Os arquivos devem ser enviados para: avatars/<ID_DO_USUARIO>/foto.jpg
-- =========================================================

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

create policy "Qualquer pessoa visualiza avatars"
on storage.objects for select
using (bucket_id = 'avatars');

create policy "Usuário envia avatar para a própria pasta"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "Usuário atualiza avatar da própria pasta"
on storage.objects for update to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "Usuário exclui avatar da própria pasta"
on storage.objects for delete to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);
