import { useState } from 'react'
import { ArrowRight, Check, ClipboardCheck, HandHeart, LockKeyhole, Puzzle, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button, Card, Input, Logo, Modal } from '../components/ui'
import ana from '../assets/ana-carolina.png'
import camila from '../assets/camila.png'

export function Landing(){
  const [roleOpen,setRoleOpen]=useState(false); const [faq,setFaq]=useState<number|null>(0); const navigate=useNavigate()
  const choose=(role:'cliente'|'psicologo')=>navigate(`/cadastro/${role}`)
  return <div className="bg-cream">
    <section className="organic-bg min-h-[720px] bg-gradient-to-br from-sage-600 via-sage-300 to-[#f8efe4] text-white">
      <header className="page-shell flex h-24 items-center justify-between"><Logo light/><nav className="hidden gap-8 text-sm md:flex"><a href="#como">Como funciona</a><a href="#duvidas">Dúvidas</a><a href="#depoimentos">Depoimentos</a><a href="#contato">Contato</a></nav><Button variant="outline" onClick={()=>navigate('/entrar')}>Entrar</Button></header>
      <div className="page-shell relative flex flex-col items-center pb-24 pt-16 text-center"><span className="mb-5 rounded-full border border-white/40 bg-white/10 px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] backdrop-blur">Cuidado que combina com você</span><h1 className="heading-display max-w-4xl text-5xl leading-[.98] sm:text-7xl lg:text-[92px]">Encontre o psicólogo<br/>ideal para <em>você</em></h1><p className="mt-7 max-w-xl text-base text-white/85 sm:text-lg">Uma forma simples, segura e personalizada de encontrar profissionais que realmente fazem sentido para o seu momento.</p>
        <div className="my-10 flex items-center gap-6"><span className="grid h-20 w-20 place-items-center rounded-full border border-white/30 bg-white/10 backdrop-blur"><HandHeart size={38}/></span><Puzzle size={66} strokeWidth={1.2}/><span className="grid h-20 w-20 place-items-center rounded-full border border-white/30 bg-white/10 backdrop-blur"><Sparkles size={36}/></span></div>
        <div className="flex w-full max-w-xl flex-col gap-3 sm:flex-row"><Button variant="outline" full onClick={()=>choose('cliente')}>Encontrar meu psicólogo</Button><Button full className="bg-sage-800 hover:bg-sage-900" onClick={()=>choose('psicologo')}>Sou psicólogo(a)</Button></div>
      </div>
    </section>

    <section id="como" className="page-shell py-24 text-center"><p className="eyebrow">Como funciona</p><h2 className="heading-display mt-3 text-4xl italic text-sage-700 sm:text-6xl">Um caminho simples<br/>para cuidar de você</h2><p className="mx-auto mt-5 max-w-lg text-sage-600">Nossa plataforma conecta você aos profissionais ideais de forma rápida, segura e personalizada.</p><div className="mt-12 grid gap-5 md:grid-cols-3">{([[ClipboardCheck,'Responder perguntas','Conte-nos sobre suas necessidades e preferências em um formulário acolhedor.'],[Sparkles,'Receber sugestões','A triagem organiza as informações e encontra perfis compatíveis.'],[HandHeart,'Escolher com segurança','Explore os perfis, compare opções e decida com mais confiança.']] as const).map(([Icon,title,text],i)=><Card key={title} className="p-7 text-left"><span className="grid h-14 w-14 place-items-center rounded-full bg-sage-100 text-sage-700"><Icon size={26}/></span><span className="mt-6 block text-xs font-bold text-sage-500">0{i+1}</span><h3 className="mt-2 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-sage-600">{text}</p></Card>)}</div></section>

    <section id="duvidas" className="relative bg-[#efe5d8] py-24"><div className="leaf right-4 top-16"/><div className="page-shell"><div className="text-center"><p className="eyebrow">FAQ</p><h2 className="heading-display mt-3 text-5xl italic text-sage-700">Dúvidas frequentes</h2><p className="mt-4 text-sage-600">Respostas simples para deixar sua experiência mais segura.</p></div><div className="mx-auto mt-10 max-w-3xl space-y-3">{[['Como o sistema encontra psicólogos compatíveis?','Cruzamos suas preferências de atendimento, objetivos, disponibilidade e faixa de valor com os perfis profissionais cadastrados.'],['O Vínculo realiza diagnósticos?','Não. A plataforma facilita o encontro entre pessoas e profissionais; qualquer avaliação clínica cabe exclusivamente ao psicólogo.'],['Preciso pagar para utilizar a plataforma?','A descoberta e a triagem são gratuitas. O pagamento da sessão é combinado conforme o valor exibido no perfil.']].map(([q,a],i)=><button key={q} onClick={()=>setFaq(faq===i?null:i)} className="surface w-full p-5 text-left"><span className="flex items-center gap-5"><strong className="text-sage-400">0{i+1}</strong><span className="flex-1 font-medium">{q}</span><span className="text-xl">{faq===i?'−':'+'}</span></span>{faq===i&&<p className="ml-11 mt-4 max-w-2xl text-sm leading-6 text-sage-600">{a}</p>}</button>)}</div></div></section>

    <section id="depoimentos" className="page-shell py-24"><div className="text-center"><p className="eyebrow">Depoimentos</p><h2 className="heading-display mt-3 text-5xl italic text-sage-700">Histórias que nos inspiram</h2></div><div className="mt-10 grid gap-5 md:grid-cols-2">{[[ana,'Mariana S.','Cliente','A triagem me ajudou a entender o que eu precisava e encontrar alguém que realmente faz sentido para mim.'],[camila,'Camila R.','Psicóloga clínica','O Vínculo me conecta com pessoas que se identificam com meu trabalho. É mais do que visibilidade, é propósito.']].map(([img,name,role,text])=><Card key={String(name)} className="flex flex-col gap-6 p-7 sm:flex-row sm:items-center"><img src={img} alt="" className="h-28 w-28 rounded-full object-cover object-top"/><div><p className="text-4xl font-serif text-sage-300">“</p><p className="leading-7">{text as string}</p><p className="mt-5 font-semibold">{name as string}</p><p className="text-xs uppercase tracking-wider text-sage-500">{role as string}</p></div></Card>)}</div></section>

    <section id="contato" className="relative bg-sage-700 py-24 text-white"><div className="page-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-sage-200">Contato</p><h2 className="heading-display mt-4 text-6xl italic">Vamos nos vincular?</h2><p className="mt-5 max-w-md text-sage-100">Fale com a gente para tirar dúvidas, sugerir melhorias ou construir uma parceria.</p></div><form className="rounded-[28px] bg-white p-6 text-ink sm:p-8" onSubmit={e=>e.preventDefault()}><div className="grid gap-4 sm:grid-cols-2"><Input label="Nome completo" placeholder="Seu nome"/><Input label="E-mail" type="email" placeholder="contato@email.com"/></div><Input label="Assunto" placeholder="Como podemos ajudar?" className="mt-1"/><label className="mt-4 block text-sm font-medium">Mensagem<textarea className="focus-ring mt-2 min-h-28 w-full rounded-xl border border-sage-200 p-4" placeholder="Escreva sua mensagem..."/></label><Button full className="mt-5">Enviar mensagem</Button></form></div></section>
    <footer className="bg-sage-800 py-8 text-sage-200"><div className="page-shell flex flex-col items-center justify-between gap-4 text-sm sm:flex-row"><Logo light/><p>© 2026 O Vínculo · Cuidado com propósito.</p><button onClick={()=>setRoleOpen(true)} className="underline">Começar agora</button></div></footer>

    <Modal open={roleOpen} onClose={()=>setRoleOpen(false)}><div className="text-center"><Logo/><h2 className="mt-5 text-2xl font-semibold">Como deseja acessar?</h2><p className="mt-2 text-sm text-sage-600">Escolha a opção que melhor descreve você.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2">{([['cliente',HandHeart,'Sou cliente','Quero encontrar o psicólogo ideal para o meu momento.'],['psicologo',ClipboardCheck,'Sou psicólogo(a)','Quero encontrar clientes e gerenciar meu perfil.']] as const).map(([role,Icon,title,text])=><button key={role} onClick={()=>choose(role)} className="rounded-2xl border border-sage-200 p-6 text-left transition hover:border-sage-500 hover:bg-sage-50"><span className="grid h-12 w-12 place-items-center rounded-full bg-sage-100"><Icon/></span><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm text-sage-600">{text}</p><ArrowRight className="mt-5" size={18}/></button>)}</div><p className="mt-6 flex items-center justify-center gap-2 text-xs text-sage-500"><LockKeyhole size={14}/>Seus dados estão protegidos com segurança.</p></Modal>
  </div>
}
