import { LoaderCircle, MessageCircle, Send } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Button, Card, EmptyState } from './ui'
import { getContact, getConversation, getConversationContacts, getCurrentUserId, sendMessage, type ChatMessage, type ConversationContact } from '../services/messages'

export function ChatPage(){
  const [params,setParams]=useSearchParams();const requested=params.get('com');const [contacts,setContacts]=useState<ConversationContact[]>([]);const [active,setActive]=useState<ConversationContact|null>(null);const [messages,setMessages]=useState<ChatMessage[]>([]);const [userId,setUserId]=useState('');const [text,setText]=useState('');const [loading,setLoading]=useState(true)
  useEffect(()=>{Promise.all([getCurrentUserId(),getConversationContacts(),requested?getContact(requested):Promise.resolve(null)]).then(([id,list,direct])=>{setUserId(id);const merged=direct&&!list.some(item=>item.id===direct.id)?[direct,...list]:list;setContacts(merged);setActive(direct??merged[0]??null)}).finally(()=>setLoading(false))},[requested])
  useEffect(()=>{if(active)getConversation(active.id).then(setMessages)},[active])
  async function submit(){if(!active||!text.trim())return;await sendMessage(active.id,text);setText('');setMessages(await getConversation(active.id));setContacts(await getConversationContacts())}
  if(loading)return <LoaderCircle className="mx-auto mt-20 animate-spin text-sage-500"/>
  return <div className="mx-auto max-w-5xl"><h1 className="text-3xl font-semibold">Mensagens</h1>{contacts.length?<Card className="mt-6 grid min-h-[540px] overflow-hidden md:grid-cols-[280px_1fr]"><aside className="border-r border-sage-100 p-3">{contacts.map(contact=><button key={contact.id} onClick={()=>{setActive(contact);setParams({com:contact.id})}} className={`mb-1 flex w-full items-center gap-3 rounded-xl p-3 text-left ${active?.id===contact.id?'bg-sage-100':'hover:bg-sage-50'}`}><img src={contact.image} className="h-10 w-10 rounded-full object-cover"/><div className="min-w-0"><strong className="block truncate text-sm">{contact.name}</strong><small className="block truncate text-sage-500">{contact.lastMessage||'Iniciar conversa'}</small></div></button>)}</aside>{active&&<section className="flex min-h-[540px] flex-col"><header className="flex items-center gap-3 border-b border-sage-100 p-4"><img src={active.image} className="h-10 w-10 rounded-full object-cover"/><strong>{active.name}</strong></header><div className="flex-1 space-y-3 overflow-auto bg-sage-50/40 p-4">{messages.length?messages.map(message=><div key={message.id} className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm ${message.senderId===userId?'ml-auto bg-sage-600 text-white':'bg-white shadow-sm'}`}>{message.content}</div>):<p className="pt-20 text-center text-sm text-sage-500">Envie a primeira mensagem.</p>}</div><form onSubmit={e=>{e.preventDefault();submit()}} className="flex gap-2 border-t border-sage-100 p-4"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Escreva uma mensagem" className="h-11 min-w-0 flex-1 rounded-full border border-sage-200 px-4 outline-none focus:border-sage-500"/><Button type="submit" aria-label="Enviar"><Send size={17}/></Button></form></section>}</Card>:<div className="mt-6"><EmptyState icon={<MessageCircle/>} title="Nenhuma conversa iniciada" text="Abra um perfil profissional ou aguarde um cliente iniciar o contato."/></div>}</div>
}
