import { CalendarDays, Check, LoaderCircle, Search, Star, X } from 'lucide-react'
import { useEffect, useState, type ReactNode } from 'react'
import { useParams } from 'react-router-dom'
import { Badge, Button, Card, EmptyState, Input } from '../../components/ui'
import { ChatPage } from '../../components/ChatPage'
import { getProfessionalAppointments, getProfessionalPatients, getProfessionalReviews, updateAppointmentStatus, type ProfessionalAppointment, type ProfessionalPatient, type ProfessionalReview } from '../../services/professionalData'

const titles:Record<string,[string,string]>={agenda:['Agenda','Atendimentos solicitados pelos clientes.'],solicitacoes:['Solicitações','Aceite ou recuse pedidos reais de consulta.'],pacientes:['Pacientes','Clientes com consultas confirmadas ou concluídas.'],avaliacoes:['Avaliações','Avaliações enviadas após consultas concluídas.'],configuracoes:['Configurações','Preferências da sua conta.']}
export function ProfessionalUtilityPage(){const {type='agenda'}=useParams();if(type==='mensagens')return <ChatPage/>;const [title,sub]=titles[type]||['Área profissional','Gerencie esta área.'];if(type==='agenda')return <AppointmentsView title={title} sub={sub}/>;if(type==='solicitacoes')return <RequestsView title={title} sub={sub}/>;if(type==='pacientes')return <PatientsView title={title} sub={sub}/>;if(type==='avaliacoes')return <ReviewsView title={title} sub={sub}/>;return <Shell title={title} sub={sub}><Card className="mt-6 p-6"><p className="text-sm text-sage-600">As preferências desta área serão conectadas em uma próxima etapa.</p></Card></Shell>}

function AppointmentsView({title,sub}:{title:string;sub:string}){const [items,setItems]=useState<ProfessionalAppointment[]>([]);const [loading,setLoading]=useState(true);async function refresh(){setItems(await getProfessionalAppointments())}useEffect(()=>{refresh().finally(()=>setLoading(false))},[]);async function conclude(id:string){await updateAppointmentStatus(id,'concluido');await refresh()}return <Shell title={title} sub={sub}>{loading?<Loading/>:items.length?<Card className="mt-6 overflow-hidden">{items.map(item=><div key={item.id} className="grid gap-3 border-b border-sage-100 p-5 last:border-0 sm:grid-cols-[90px_1fr_auto]"><strong>{item.time}</strong><div><p className="font-semibold">{item.clientName}</p><p className="text-xs text-sage-500">{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR')} · Consulta {item.mode}</p></div><div className="flex items-center gap-2"><Status status={item.status}/>{item.status==='confirmado'&&<Button variant="outline" onClick={()=>conclude(item.id)}>Concluir</Button>}</div></div>)}</Card>:<Empty text="Nenhum agendamento recebido."/>}</Shell>}
function RequestsView({title,sub}:{title:string;sub:string}){const [items,setItems]=useState<ProfessionalAppointment[]>([]);const [loading,setLoading]=useState(true);async function refresh(){setItems((await getProfessionalAppointments()).filter(item=>item.status==='pendente'))}useEffect(()=>{refresh().finally(()=>setLoading(false))},[]);async function update(id:string,status:'confirmado'|'cancelado'){await updateAppointmentStatus(id,status);await refresh()}return <Shell title={title} sub={sub}>{loading?<Loading/>:items.length?<div className="mt-6 space-y-3">{items.map(item=><Card key={item.id} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><img src={item.clientImage} className="h-14 w-14 rounded-full object-cover"/><div><h3 className="font-semibold">{item.clientName}</h3><p className="text-sm text-sage-500">{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR')} às {item.time}</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={()=>update(item.id,'cancelado')}><X size={16}/>Recusar</Button><Button onClick={()=>update(item.id,'confirmado')}><Check size={16}/>Aceitar</Button></div></Card>)}</div>:<Empty text="Nenhuma solicitação pendente."/>}</Shell>}
function PatientsView({title,sub}:{title:string;sub:string}){const [items,setItems]=useState<ProfessionalPatient[]>([]);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);useEffect(()=>{getProfessionalPatients().then(setItems).finally(()=>setLoading(false))},[]);const filtered=items.filter(item=>item.name.toLowerCase().includes(search.toLowerCase()));return <Shell title={title} sub={sub}>{loading?<Loading/>:<><div className="mt-6"><Input placeholder="Buscar paciente" icon={<Search size={17}/>} value={search} onChange={e=>setSearch(e.target.value)}/></div>{filtered.length?<div className="mt-4 grid gap-4 sm:grid-cols-2">{filtered.map(item=><Card key={item.id} className="flex items-center gap-4 p-5"><img src={item.image} className="h-14 w-14 rounded-full object-cover"/><div><h3 className="font-semibold">{item.name}</h3><p className="text-xs text-sage-500">{item.sessions} consulta(s)</p></div></Card>)}</div>:<Empty text="Nenhum paciente com consulta confirmada."/>}</>}</Shell>}
function ReviewsView({title,sub}:{title:string;sub:string}){const [items,setItems]=useState<ProfessionalReview[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{getProfessionalReviews().then(setItems).finally(()=>setLoading(false))},[]);return <Shell title={title} sub={sub}>{loading?<Loading/>:items.length?<div className="mt-6 grid gap-4 sm:grid-cols-2">{items.map(item=><Card key={item.id} className="p-6"><p className="flex text-amber-400">{Array.from({length:item.rating},(_,i)=><Star key={i} size={16} fill="currentColor"/>)}</p><p className="mt-3">{item.comment||'Avaliação sem comentário.'}</p><p className="mt-4 text-sm font-semibold">{item.clientName}</p></Card>)}</div>:<Empty text="Você ainda não recebeu avaliações."/>}</Shell>}
function Status({status}:{status:string}){return <Badge tone={status==='pendente'?'amber':status==='cancelado'?'pink':'sage'}>{status}</Badge>}
function Loading(){return <LoaderCircle className="mx-auto mt-20 animate-spin text-sage-500"/>}
function Empty({text}:{text:string}){return <div className="mt-6"><EmptyState icon={<CalendarDays/>} title={text} text="Os dados aparecerão aqui quando houver movimentação real entre as contas."/></div>}
function Shell({title,sub,children}:{title:string;sub:string;children:ReactNode}){return <div className="mx-auto max-w-5xl"><h1 className="text-3xl font-semibold text-sage-700">{title}</h1><p className="mt-2 text-sage-600">{sub}</p>{children}</div>}
