import { CalendarDays, ChevronLeft, ChevronRight, Clock, Lock, Plus, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Badge, Button, Card, Modal } from '../../components/ui'
import { addAvailability, deleteAvailability, getAvailability, type AvailabilitySlot } from '../../services/availability'
import { getOwnProfessionalProfile } from '../../services/professionalProfile'

const days=Array.from({length:35},(_,i)=>i<2?30+i:i-1)
export function Availability(){
  const [selected,setSelected]=useState(23); const [tab,setTab]=useState('Calendário'); const [modal,setModal]=useState(false); const [psychologistId,setPsychologistId]=useState(''); const [times,setTimes]=useState<AvailabilitySlot[]>([]); const selectedDate=`2026-06-${String(selected).padStart(2,'0')}`
  useEffect(()=>{getOwnProfessionalProfile().then(profile=>setPsychologistId(profile.id))},[])
  useEffect(()=>{if(psychologistId)getAvailability(psychologistId,selectedDate).then(setTimes)},[psychologistId,selectedDate])
  async function remove(id:string){await deleteAvailability(id);setTimes(items=>items.filter(item=>item.id!==id))}
  async function add(){if(!psychologistId)return;await addAvailability(psychologistId,selectedDate,'18:00');setTimes(await getAvailability(psychologistId,selectedDate));setModal(false)}
  return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-semibold text-sage-700">Disponibilidade</h1><p className="mt-2 max-w-xl text-sage-600">Gerencie seus horários de atendimento, visualize sua agenda e bloqueie períodos indisponíveis.</p><div className="mt-7 flex gap-6 border-b border-sage-200">{['Calendário','Horários','Bloqueios'].map(x=><button key={x} onClick={()=>setTab(x)} className={`border-b-2 px-2 pb-3 text-sm ${tab===x?'border-sage-600 font-semibold text-sage-700':'border-transparent text-sage-500'}`}>{x}</button>)}</div>
  <div className="mt-5 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><Card className="p-6"><div className="flex items-center justify-between"><button className="rounded-full border p-2"><ChevronLeft size={17}/></button><h2 className="font-semibold">Junho de 2026</h2><button className="rounded-full border p-2"><ChevronRight size={17}/></button></div><div className="mt-6 grid grid-cols-7 gap-2 text-center text-sm"><span>D</span><span>S</span><span>T</span><span>Q</span><span>Q</span><span>S</span><span>S</span>{days.map((d,i)=><button key={i} onClick={()=>setSelected(d)} className={`relative aspect-square rounded-full ${selected===d?'bg-sage-500 text-white':i<2||d<1?'text-sage-300':'hover:bg-sage-50'}`}>{d}<i className={`absolute bottom-1 left-1/2 h-1 w-1 -translate-x-1/2 rounded-full ${[5,9,17,19,22,27,29,30].includes(d)?'bg-sage-400':'bg-transparent'}`}/></button>)}</div><div className="mt-6 flex flex-wrap gap-4 text-[11px] text-sage-500"><span>● Com horários disponíveis</span><span className="text-sage-300">● Sem horários</span><span className="text-rose-300">● Bloqueado</span></div></Card>
  <Card className="p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-sage-100"><CalendarDays size={19}/></span><div><h2 className="font-semibold">Dia {selected} de junho de 2026</h2><p className="text-xs text-sage-500">{times.length} horários disponíveis</p></div></div><div className="mt-5 space-y-2">{times.map(slot=><div key={slot.id} className="flex items-center rounded-xl border border-sage-100 p-3"><Clock size={16} className="mr-3 text-sage-500"/><strong className="text-sm">{slot.time}</strong><span className="ml-8 text-xs text-sage-500">50 min</span><Badge><span className="mr-1 h-1.5 w-1.5 rounded-full bg-sage-500"/>Disponível</Badge><button onClick={()=>remove(slot.id)} className="ml-auto rounded-full p-2 text-sage-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={15}/></button></div>)}</div><Button full variant="outline" className="mt-4" onClick={()=>setModal(true)}><Plus size={16}/>Adicionar horário</Button></Card></div>
  <Card className="mt-5 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><h2 className="flex items-center gap-2 font-semibold"><Lock size={18}/>Próximos bloqueios</h2><Button variant="outline" className="min-h-9" onClick={()=>setModal(true)}>+ Bloquear período</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['28 a 30 de junho','Viagem'],['7 de julho','Feriado'],['8 a 25 de agosto','Férias'],['7 de setembro','Feriado']].map(([d,n])=><div key={d} className="rounded-2xl bg-rose-50 p-4"><p className="text-sm font-semibold text-rose-700">{d}</p><p className="text-xs text-rose-500">{n}</p></div>)}</div></Card>
  <Modal open={modal} onClose={()=>setModal(false)}><h2 className="text-2xl font-semibold">Adicionar disponibilidade</h2><p className="mt-2 text-sm text-sage-500">Adicione o horário das 18:00 para {selected} de junho.</p><input type="time" value="18:00" readOnly className="focus-ring mt-6 h-12 w-full rounded-xl border border-sage-200 px-4"/><Button full className="mt-5" onClick={add}>Salvar horário</Button></Modal></div>
}
