import { ArrowUpRight, CalendarDays, Crown, Eye, Heart, Lightbulb, MessageCircle, Star, Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Badge, Button, Card } from '../../components/ui'
import { appointments, requests } from '../../data/mockData'
import { useCurrentProfile } from '../../hooks/useCurrentProfile'

export function Dashboard(){
  const navigate=useNavigate(); const metrics=[[Eye,'Visualizações','1.248','+12% este mês'],[Heart,'Favoritos','342','+8% este mês'],[MessageCircle,'Solicitações','26','5 aguardando'],[Crown,'Plano atual','Profissional','Renova em 16/08']] as const
  const profile=useCurrentProfile()
  return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-semibold text-sage-700">Olá{profile?.name?`, ${profile.name.split(' ')[0]}`:''}!</h1><p className="mt-1 text-sage-600">Aqui está o resumo do seu consultório hoje.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([Icon,label,value,note])=><Card key={label} className="p-5"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-sage-100 text-sage-700"><Icon size={21}/></span><ArrowUpRight size={16} className="text-sage-400"/></div><p className="mt-4 text-sm text-sage-600">{label}</p><strong className="text-2xl font-medium">{value}</strong><p className="mt-2 text-xs text-sage-500">{note}</p></Card>)}</div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_1fr_.75fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-sage-100 p-5"><h2 className="flex items-center gap-2 font-semibold"><CalendarDays size={18}/>Agenda de hoje</h2><Button variant="soft" className="min-h-8 px-3 text-xs" onClick={()=>navigate('/psicologo/agenda')}>Ver agenda</Button></div><div>{appointments.map(([time,name,mode,status])=><div key={time} className="grid grid-cols-[55px_1fr_auto] items-center gap-3 border-b border-sage-100 px-5 py-3 last:border-0"><strong className="text-sm text-sage-700">{time}</strong><div><p className="text-sm font-semibold">{name}</p><p className="text-xs text-sage-500">Consulta {mode.toLowerCase()}</p></div><Badge tone={status==='Pendente'?'amber':'sage'}>{status}</Badge></div>)}</div></Card>
    <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-sage-100 p-5"><h2 className="flex items-center gap-2 font-semibold"><MessageCircle size={18}/>Solicitações recentes</h2><button onClick={()=>navigate('/psicologo/solicitacoes')} className="text-xs text-sage-500">Ver todas</button></div><div>{requests.map(([name,date,img])=><div key={String(name)} className="flex items-center gap-3 border-b border-sage-100 p-4 last:border-0"><img src={String(img)} className="h-10 w-10 rounded-full object-cover object-top"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{String(name)}</p><p className="text-xs text-sage-500">Solicitou uma consulta · {String(date)}</p></div><Badge tone="amber">Pendente</Badge></div>)}</div></Card>
    <div className="space-y-5"><Card className="p-5"><h2 className="flex items-center gap-2 font-semibold"><Users size={18}/>Resumo do perfil</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt>Avaliação</dt><dd className="text-amber-500">★ 4,9</dd></div><div className="flex justify-between"><dt>Taxa de resposta</dt><dd>92%</dd></div><div className="flex justify-between"><dt>Consultas</dt><dd>398</dd></div><div className="flex justify-between"><dt>Membro desde</dt><dd>Mar/2022</dd></div></dl></Card><Card className="bg-sage-100 p-5"><Lightbulb className="text-sage-700"/><h3 className="mt-3 font-semibold">Dica para você</h3><p className="mt-2 text-sm text-sage-600">Mantenha sua disponibilidade atualizada para receber mais solicitações.</p><button onClick={()=>navigate('/psicologo/disponibilidade')} className="mt-4 text-xs font-semibold underline">Atualizar disponibilidade</button></Card></div></div>
    <Card className="mt-5 p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><Star size={18}/>Avaliações recentes</h2><button className="text-xs text-sage-500">Ver todas</button></div><div className="mt-4 grid divide-y divide-sage-100 sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-4">{[['Mariana S.','Me senti muito acolhida.'],['Lucas F.','Excelente profissional!'],['Fernanda A.','Atendimento muito bom.'],['Alice S.','Profissional super querida!']].map(([n,t])=><div key={n} className="p-3"><p className="text-amber-400">★★★★★</p><p className="mt-1 text-sm">{t}</p><small className="text-sage-500">Paciente: {n}</small></div>)}</div></Card></div>
}
