import { AlertTriangle, Camera, Check, LoaderCircle, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import placeholderAvatar from '../../assets/avatar-placeholder.svg'
import { Button, Card, Input } from '../../components/ui'
import { getOwnProfessionalProfile, saveProfessionalProfile, uploadProfessionalAvatar, type ProfessionalProfile } from '../../services/professionalProfile'
import { PhotoAdjuster } from '../../components/PhotoAdjuster'

const allSpecialties=['Ansiedade','Autoestima','Relacionamentos','TDAH','Burnout','Depressão','Luto','Traumas']

export function EditProfile(){
  const [profile,setProfile]=useState<ProfessionalProfile|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [editingFile,setEditingFile]=useState<File|null>(null)
  useEffect(()=>{getOwnProfessionalProfile().then(setProfile).catch(()=>setMessage('Não foi possível carregar o perfil.')).finally(()=>setLoading(false))},[])
  const set=<K extends keyof ProfessionalProfile>(key:K,value:ProfessionalProfile[K])=>setProfile(current=>current?{...current,[key]:value}:current)
  const toggleSpecialty=(name:string)=>profile&&set('specialties',profile.specialties.includes(name)?profile.specialties.filter(item=>item!==name):[...profile.specialties,name])
  async function save(){if(!profile)return;setSaving(true);setMessage('');try{await saveProfessionalProfile(profile);setProfile(current=>current?{...current,active:Boolean(current.avatarUrl)}:current);setMessage('Alterações salvas com sucesso.')}catch{setMessage('Não foi possível salvar as alterações.')}finally{setSaving(false)}}
  async function upload(file?:File){if(!file||!profile)return;setSaving(true);try{const url=await uploadProfessionalAvatar(file);setProfile(current=>current?{...current,avatarUrl:url,active:true}:current);setMessage('Foto atualizada com sucesso. Seu perfil agora pode aparecer na busca.')}catch{setMessage('Não foi possível enviar a foto.')}finally{setSaving(false)}}

  if(loading)return <div className="grid min-h-80 place-items-center"><LoaderCircle className="animate-spin text-sage-500" size={34}/></div>
  if(!profile)return <Card className="p-10 text-center"><h1 className="text-xl font-semibold">Perfil profissional não encontrado</h1><p className="mt-2 text-sage-500">{message}</p></Card>
  return <div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold text-sage-700">Meu perfil</h1><p className="mt-2 text-sage-600">Essas informações aparecem para os clientes na descoberta.</p></div>{message&&<span className="flex items-center gap-2 text-sm text-sage-600"><Check size={17}/>{message}</span>}</div>{(!profile.active||!profile.avatarUrl)&&<Card className="mt-6 border border-amber-200 bg-amber-50 p-5 text-amber-800"><h2 className="flex items-center gap-2 font-semibold"><AlertTriangle size={18}/>Seu perfil ainda não está publicado</h2><p className="mt-2 text-sm leading-6">Para aparecer na busca dos clientes, adicione uma foto profissional. Enquanto isso não for feito, seu perfil fica salvo, mas invisível na descoberta.</p></Card>}
  <Card className="mt-7 p-6 sm:p-8"><div className="flex flex-col items-center gap-6 border-b border-sage-100 pb-7 sm:flex-row"><div className="relative"><img src={profile.avatarUrl||placeholderAvatar} alt={profile.name} className="h-32 w-32 rounded-[34px] object-cover object-top"/><label className="absolute -bottom-2 -right-2 cursor-pointer rounded-full bg-sage-600 p-3 text-white shadow"><Camera size={17}/><input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{setEditingFile(e.target.files?.[0]||null);e.target.value=''}}/></label></div><div><h2 className="text-xl font-semibold">{profile.name}</h2><p className="text-sm text-sage-500">CRP {profile.crp}</p><p className="mt-2 max-w-md text-sm text-sage-600">Uma foto clara e uma apresentação acolhedora ajudam pacientes a se sentirem seguros para dar o primeiro passo.</p><button type="button" onClick={()=>document.querySelector<HTMLInputElement>('#professional-photo-input')?.click()} className="mt-3 text-sm font-semibold text-sage-700 underline">Trocar e ajustar foto</button><input id="professional-photo-input" type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{setEditingFile(e.target.files?.[0]||null);e.target.value=''}}/></div></div>
  <div className="mt-7 grid gap-5 sm:grid-cols-2"><Input label="Nome profissional" value={profile.name} onChange={e=>set('name',e.target.value)}/><Input label="CRP" value={profile.crp} onChange={e=>set('crp',e.target.value)}/><Input label="Estado do CRP" value={profile.crpState} onChange={e=>set('crpState',e.target.value)}/><Input label="Valor por sessão" type="number" min="0" value={profile.price} onChange={e=>set('price',Number(e.target.value))}/><Input label="Anos de experiência" type="number" min="0" value={profile.experience} onChange={e=>set('experience',Number(e.target.value))}/><label className="text-sm font-medium">Modalidade<select value={profile.modality} onChange={e=>set('modality',e.target.value as ProfessionalProfile['modality'])} className="mt-2 h-12 w-full rounded-xl border border-sage-200 bg-white px-4"><option value="online">Online</option><option value="presencial">Presencial</option><option value="ambos">Ambos</option></select></label></div><label className="mt-5 block text-sm font-medium">Biografia profissional<textarea value={profile.bio} onChange={e=>set('bio',e.target.value)} className="focus-ring mt-2 min-h-32 w-full rounded-xl border border-sage-200 p-4"/></label><div className="mt-6"><h3 className="text-sm font-medium">Especialidades</h3><div className="mt-3 flex flex-wrap gap-2">{allSpecialties.map(name=><button type="button" key={name} onClick={()=>toggleSpecialty(name)} className={`rounded-full border px-4 py-2 text-sm ${profile.specialties.includes(name)?'border-sage-500 bg-sage-100 text-sage-800':'border-sage-200 text-sage-500'}`}>{profile.specialties.includes(name)&&'✓ '}{name}</button>)}</div></div><Button className="mt-8" disabled={saving} onClick={save}>{saving?<LoaderCircle className="animate-spin" size={17}/>:<Save size={17}/>}Salvar alterações</Button></Card><PhotoAdjuster file={editingFile} onCancel={()=>setEditingFile(null)} onConfirm={adjusted=>{setEditingFile(null);upload(adjusted)}}/></div>
}
