import { useParams } from 'react-router-dom'
import type { ReactNode } from 'react'
import { CalendarDays, Check, Clock, MessageCircle, Search, Settings, Star, UserRound, UsersRound } from 'lucide-react'
import { appointments, requests } from '../../data/mockData'
import { Badge, Button, Card, EmptyState, Input } from '../../components/ui'

const titles:Record<string,[string,string]>={agenda:['Agenda','Acompanhe os atendimentos e organize a sua rotina.'],solicitacoes:['Solicitações','Analise e responda aos novos pedidos de consulta.'],pacientes:['Pacientes','Pessoas que já construíram um vínculo com seu trabalho.'],avaliacoes:['Avaliações','Veja o que seus pacientes compartilharam sobre a experiência.'],configuracoes:['Configurações','Ajuste preferências, notificações e segurança da conta.']}
export function ProfessionalUtilityPage(){
  const {type='agenda'}=useParams(); const [title,sub]=titles[type]||['Área profissional','Gerencie esta área do seu consultório.']
  if(type==='agenda') return <Shell title={title} sub={sub}><Card className="mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-sage-100 p-5"><strong>Terça-feira, 16 de junho</strong><Button variant="outline">+ Novo horário</Button></div>{appointments.map(([time,name,mode,status])=><div key={time} className="grid grid-cols-[70px_1fr_auto] items-center gap-3 border-b border-sage-100 p-5 last:border-0"><strong>{time}</strong><div><p className="font-semibold">{name}</p><p className="text-xs text-sage-500">Consulta {mode.toLowerCase()} · 50 min</p></div><Badge tone={status==='Pendente'?'amber':'sage'}>{status}</Badge></div>)}</Card></Shell>
  if(type==='solicitacoes') return <Shell title={title} sub={sub}><div className="mt-6 space-y-3">{requests.map(([name,date,img])=><Card key={String(name)} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><img src={String(img)} className="h-14 w-14 rounded-full object-cover object-top"/><div><h3 className="font-semibold">{String(name)}</h3><p className="text-sm text-sage-500">Solicitou consulta online · {String(date)}</p></div></div><div className="flex gap-2"><Button variant="outline">Recusar</Button><Button><Check size={16}/>Aceitar</Button></div></Card>)}</div></Shell>
  if(type==='pacientes') return <Shell title={title} sub={sub}><div className="mt-6"><Input placeholder="Buscar paciente" icon={<Search size={17}/>}/><div className="mt-4 grid gap-4 sm:grid-cols-2">{['Mariana Santos','Carlos Eduardo','Juliana Pereira','Rafael Lima'].map((n,i)=><Card key={n} className="p-5"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-sage-100"><UserRound/></span><div><h3 className="font-semibold">{n}</h3><p className="text-xs text-sage-500">{8+i*3} sessões realizadas</p></div></div><Button variant="ghost" className="mt-4">Ver histórico</Button></Card>)}</div></div></Shell>
  if(type==='avaliacoes') return <Shell title={title} sub={sub}><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['Mariana S.','Me senti muito acolhida desde a primeira sessão.'],['Lucas F.','Excelente profissional, atenciosa e empática.'],['Fernanda A.','Atendimento muito bom. Recomendo!'],['Alice S.','Uma profissional super querida e competente.']].map(([n,t])=><Card key={n} className="p-6"><p className="text-amber-400">★★★★★</p><p className="mt-3 leading-6">“{t}”</p><p className="mt-4 text-sm font-semibold">{n}</p><small className="text-sage-500">Paciente verificado</small></Card>)}</div></Shell>
  return <Shell title={title} sub={sub}><Card className="mt-6 p-6"><h2 className="font-semibold">Notificações</h2>{['Novas solicitações','Lembretes de agenda','Novas avaliações'].map(x=><label key={x} className="mt-4 flex items-center justify-between border-b border-sage-100 pb-4 text-sm"><span>{x}</span><input type="checkbox" defaultChecked className="h-5 w-5 accent-sage-600"/></label>)}<h2 className="mt-7 font-semibold">Segurança</h2><Button variant="outline" className="mt-4">Alterar senha</Button></Card></Shell>
}
function Shell({title,sub,children}:{title:string;sub:string;children:ReactNode}){return <div className="mx-auto max-w-5xl"><h1 className="text-3xl font-semibold text-sage-700">{title}</h1><p className="mt-2 text-sage-600">{sub}</p>{children}</div>}
