import { CalendarDays, Check, ChevronLeft, Clock, PartyPopper, ShieldCheck } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Button, Card, Stepper } from '../../components/ui'
import { buscarPsicologoPorId, type ListedPsychologist } from '../../services/psychologists'
import { createAppointment } from '../../services/appointments'
import { getUpcomingAvailability, type AvailabilitySlot } from '../../services/availability'

const formatDate=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'})

export function Booking(){
  const {id}=useParams();const navigate=useNavigate();const [person,setPerson]=useState<ListedPsychologist|null>(null);const [slots,setSlots]=useState<AvailabilitySlot[]>([]);const [selected,setSelected]=useState<AvailabilitySlot|null>(null);const [step,setStep]=useState(1);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{if(!id){setLoading(false);return}Promise.all([buscarPsicologoPorId(id),getUpcomingAvailability(id)]).then(([profile,available])=>{setPerson(profile);setSlots(available);setSelected(available[0]??null)}).catch(()=>setError('Não foi possível carregar a agenda.')).finally(()=>setLoading(false))},[id])
  const dates=useMemo(()=>[...new Set(slots.map(slot=>slot.date))],[slots]);const selectedDate=selected?.date??dates[0];const daySlots=slots.filter(slot=>slot.date===selectedDate)
  if(loading)return <div className="grid min-h-80 place-items-center text-sage-500">Carregando agenda...</div>
  if(!person)return <Card className="mx-auto max-w-xl p-10 text-center"><h1 className="text-2xl font-semibold">Profissional não encontrado</h1><Button className="mt-6" onClick={()=>navigate('/cliente/descobrir')}>Voltar</Button></Card>
  async function confirm(){if(!selected)return;setSaving(true);setError('');try{await createAppointment({availabilityId:selected.id,mode:person!.mode.toLowerCase().includes('presencial')&&!person!.mode.toLowerCase().includes('online')?'presencial':'online'});setStep(3)}catch(exception){setError(exception instanceof Error?exception.message:'Este horário não está mais disponível.')}finally{setSaving(false)}}
  return <div className="mx-auto max-w-4xl"><button onClick={()=>navigate(-1)} className="mb-5 flex items-center gap-1 text-sm text-sage-600"><ChevronLeft size={18}/>Voltar ao perfil</button><h1 className="text-3xl font-semibold text-sage-700">Agendar consulta</h1><p className="mt-2 text-sage-600">Aqui aparecem somente os horários publicados por {person.name}.</p><div className="my-7"><Stepper current={step} total={3} labels={['Escolher horário','Confirmação','Concluído']}/></div>
  {step===1&&<Card className="p-6">{slots.length?<><h2 className="flex items-center gap-2 font-semibold"><CalendarDays size={19}/>Escolha a data</h2><div className="mt-4 flex flex-wrap gap-2">{dates.map(date=><button key={date} onClick={()=>setSelected(slots.find(slot=>slot.date===date)??null)} className={`rounded-2xl border px-4 py-3 text-sm ${selectedDate===date?'border-sage-500 bg-sage-500 text-white':'border-sage-200'}`}>{formatDate(date)}</button>)}</div><h2 className="mt-6 flex items-center gap-2 font-semibold"><Clock size={19}/>Horários disponíveis</h2><div className="mt-4 flex flex-wrap gap-2">{daySlots.map(slot=><button key={slot.id} onClick={()=>setSelected(slot)} className={`rounded-full border px-5 py-2 text-sm ${selected?.id===slot.id?'border-sage-500 bg-sage-100 text-sage-800':'border-sage-200'}`}>{slot.time}</button>)}</div><Button full className="mt-7" disabled={!selected} onClick={()=>setStep(2)}>Continuar</Button></>:<div className="py-10 text-center"><CalendarDays className="mx-auto text-sage-400" size={34}/><h2 className="mt-4 text-xl font-semibold">Sem horários disponíveis</h2><p className="mt-2 text-sage-500">Este profissional ainda não publicou horários futuros.</p></div>}</Card>}
  {step===2&&selected&&<Card className="mx-auto max-w-2xl p-7"><h2 className="text-center text-2xl font-semibold">Confirme seu agendamento</h2><div className="mt-7 rounded-2xl bg-sage-50 p-5"><div className="flex items-center gap-4"><img src={person.image} className="h-16 w-16 rounded-full object-cover"/><div><strong>{person.name}</strong><p className="text-sm text-sage-500">CRP {person.crp}</p></div></div><div className="mt-5 border-t border-sage-200 pt-5 text-sm"><p>{formatDate(selected.date)}, às {selected.time}</p><p className="mt-1">R$ {person.price.toFixed(2).replace('.',',')}</p></div></div><p className="mt-5 flex gap-2 text-xs text-sage-500"><ShieldCheck size={16}/>O profissional receberá a solicitação nesta mesma conta.</p>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-7 flex gap-3"><Button variant="outline" full onClick={()=>setStep(1)}>Editar</Button><Button full disabled={saving} onClick={confirm}>{saving?'Enviando...':'Confirmar'}</Button></div></Card>}
  {step===3&&selected&&<Card className="mx-auto max-w-2xl p-9 text-center"><PartyPopper className="mx-auto text-sage-600" size={42}/><h2 className="mt-5 text-3xl font-semibold">Consulta solicitada!</h2><p className="mt-3 text-sage-600">{person.name} verá a solicitação no próprio painel.</p><p className="mt-5 flex items-center justify-center gap-2"><Check size={17}/>{formatDate(selected.date)}, às {selected.time}</p><Button className="mt-7" onClick={()=>navigate('/cliente/agendamentos')}>Ver meus agendamentos</Button></Card>}
  </div>
}
