import { CalendarDays, Check, ChevronLeft, Clock, CreditCard, PartyPopper, ShieldCheck, UserRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Button, Card, Input, Stepper } from '../../components/ui'
import { buscarPsicologoPorId, type ListedPsychologist } from '../../services/psychologists'
import { createAppointment } from '../../services/appointments'

const availableDates=[{label:'Ter 14/07',value:'2026-07-14'},{label:'Qua 15/07',value:'2026-07-15'},{label:'Qui 16/07',value:'2026-07-16'},{label:'Sex 17/07',value:'2026-07-17'},{label:'Seg 20/07',value:'2026-07-20'}]

export function Booking(){
  const {id}=useParams(); const [p,setP]=useState<ListedPsychologist|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [step,setStep]=useState(1); const [date,setDate]=useState(availableDates[0]); const [time,setTime]=useState('14:00'); const navigate=useNavigate()
  useEffect(()=>{if(!id){setLoading(false);return}buscarPsicologoPorId(id).then(setP).finally(()=>setLoading(false))},[id])
  if(loading)return <div className="grid min-h-80 place-items-center"><span className="text-sage-500">Carregando profissional...</span></div>
  if(!p)return <Card className="mx-auto max-w-xl p-10 text-center"><h1 className="text-2xl font-semibold">Profissional não encontrado</h1><p className="mt-2 text-sage-500">Escolha outro psicólogo na área de descoberta.</p><Button className="mt-6" onClick={()=>navigate('/cliente/descobrir')}>Voltar para mais procurados</Button></Card>
  async function confirm(){setSaving(true);setError('');try{await createAppointment({psychologistId:p!.id,date:date.value,time,price:p!.price,mode:'online'});setStep(3)}catch{setError('Não foi possível enviar a solicitação. Tente novamente.')}finally{setSaving(false)}}
  return <div className="mx-auto max-w-5xl"><button onClick={()=>navigate(-1)} className="mb-5 flex items-center gap-1 text-sm text-sage-600"><ChevronLeft size={18}/>Voltar ao perfil</button><h1 className="text-3xl font-semibold text-sage-700">Agendar consulta</h1><p className="mt-2 text-sage-600">Selecione a data e o horário que prefere.</p><div className="my-7"><Stepper current={step} total={3} labels={['Dados e horário','Confirmação','Concluído']}/></div>
  {step===1&&<div className="grid gap-5 lg:grid-cols-[1fr_320px]"><Card className="p-6"><h2 className="flex items-center gap-2 font-semibold"><UserRound size={19}/>Seus dados</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><Input label="CPF" placeholder="000.000.000-00"/><Input label="Telefone" placeholder="(00) 00000-0000"/><Input label="Nascimento" type="date"/></div><hr className="my-6 border-sage-100"/><h2 className="flex items-center gap-2 font-semibold"><CalendarDays size={19}/>Escolha a data</h2><div className="mt-4 flex gap-2 overflow-auto pb-2">{availableDates.map(item=><button key={item.value} onClick={()=>setDate(item)} className={`min-w-24 rounded-2xl border p-3 text-sm ${date.value===item.value?'border-sage-500 bg-sage-500 text-white':'border-sage-200'}`}>{item.label}</button>)}</div><h2 className="mt-5 flex items-center gap-2 font-semibold"><Clock size={19}/>Escolha o horário</h2><div className="mt-4 grid grid-cols-4 gap-2">{['09:00','10:00','11:00','14:00','15:00','16:00','17:00','18:00'].map(x=><button key={x} onClick={()=>setTime(x)} className={`rounded-full border py-2 text-sm ${time===x?'border-sage-500 bg-sage-100 text-sage-800':'border-sage-200'}`}>{x}</button>)}</div><Button full className="mt-7" onClick={()=>setStep(2)}>Continuar</Button></Card><ProfessionalCard person={p}/></div>}
  {step===2&&<Card className="mx-auto max-w-2xl p-7"><h2 className="text-center text-2xl font-semibold">Confirme seu agendamento</h2><div className="mt-7 rounded-2xl bg-sage-50 p-5"><div className="flex items-center gap-4"><img src={p.image} className="h-16 w-16 rounded-full object-cover object-top"/><div><strong>{p.name}</strong><p className="text-sm text-sage-500">CRP {p.crp} · Consulta online</p></div></div><div className="mt-5 grid gap-3 border-t border-sage-200 pt-5 sm:grid-cols-3"><span className="text-sm"><CalendarDays className="mb-1" size={18}/>{date.label}</span><span className="text-sm"><Clock className="mb-1" size={18}/>{time} · 50 min</span><span className="text-sm"><CreditCard className="mb-1" size={18}/>R$ {p.price},00</span></div></div><p className="mt-5 flex items-start gap-2 text-xs text-sage-500"><ShieldCheck size={16}/>O profissional receberá a solicitação para confirmar.</p>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-7 flex gap-3"><Button variant="outline" full onClick={()=>setStep(1)}>Editar</Button><Button full disabled={saving} onClick={confirm}>{saving?'Enviando...':'Confirmar agendamento'}</Button></div></Card>}
  {step===3&&<Card className="mx-auto max-w-2xl p-9 text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-sage-100 text-sage-700"><PartyPopper size={34}/></span><h2 className="mt-6 text-3xl font-semibold text-sage-700">Consulta solicitada!</h2><p className="mx-auto mt-3 max-w-md text-sage-600">Sua solicitação para {p.name} foi enviada. Avisaremos assim que o horário for confirmado.</p><div className="mx-auto mt-7 max-w-sm rounded-2xl bg-sage-50 p-5 text-left text-sm"><p className="flex items-center gap-2"><Check size={17}/><strong>{date.label}, às {time}</strong></p><p className="mt-2 text-sage-500">Consulta online · 50 minutos</p></div><Button className="mt-7" onClick={()=>navigate('/cliente/agendamentos')}>Ver meus agendamentos</Button></Card>}
  </div>
}

function ProfessionalCard({person:p}:{person:ListedPsychologist}){return <Card className="h-fit p-6"><p className="text-sm font-semibold text-sage-500">Profissional selecionado</p><div className="mt-4 flex items-center gap-4"><img src={p.image} alt="" className="h-20 w-20 rounded-full object-cover object-top"/><div><h3 className="font-semibold">{p.name}</h3><p className="text-xs text-sage-500">Psicólogo(a)</p><p className="mt-1 text-sm text-amber-500">★ {p.rating||'Novo'}</p></div></div><div className="mt-5 border-t border-sage-100 pt-4 text-sm text-sage-600"><p>{p.experience} anos de experiência</p><p className="mt-1">R$ {p.price} por sessão</p></div></Card>}
