import { CalendarDays, Check, ChevronLeft, Clock, Heart, LoaderCircle, MessageCircle, ShieldCheck, Star, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Badge, Button, Card } from '../../components/ui'
import { buscarPsicologoPorId, type ListedPsychologist } from '../../services/psychologists'

export function PsychologistProfile(){
  const {id}=useParams(); const navigate=useNavigate(); const [p,setP]=useState<ListedPsychologist|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{if(!id){setError('Perfil inválido.');setLoading(false);return}buscarPsicologoPorId(id).then(person=>person?setP(person):setError('Este perfil não existe ou ainda não está ativo.')).catch(()=>setError('Não foi possível carregar este perfil.')).finally(()=>setLoading(false))},[id])
  const matches=JSON.parse(sessionStorage.getItem('vinculo:compatibilidades')||'{}') as Record<string,number>
  const compatibility=p?matches[p.id]:undefined
  if(loading)return <div className="grid min-h-80 place-items-center"><LoaderCircle className="animate-spin text-sage-500" size={34}/></div>
  if(!p)return <Card className="mx-auto max-w-xl p-10 text-center"><h1 className="text-2xl font-semibold">Perfil não encontrado</h1><p className="mt-3 text-sage-500">{error}</p><Button className="mt-6" onClick={()=>navigate('/cliente/descobrir')}>Voltar para mais procurados</Button></Card>
  return <div className="mx-auto max-w-6xl"><button onClick={()=>navigate(-1)} className="mb-6 flex items-center gap-1 text-sm text-sage-600"><ChevronLeft size={18}/>Voltar aos resultados</button>
    <section className="relative grid gap-7 lg:grid-cols-[260px_1fr]"><div className="relative"><img src={p.image} alt={`Foto de ${p.name}`} className="h-[310px] w-full rounded-[36px] object-cover object-top shadow-soft"/><Badge tone="sage"><ShieldCheck size={13} className="mr-1"/>Perfil verificado</Badge></div><div>{compatibility&&<Badge>{compatibility}% compatível com você</Badge>}<h1 className={`${compatibility?'mt-4':''} text-4xl font-semibold text-sage-700`}>{p.name}</h1><p className="mt-1 text-sage-500">Psicólogo(a) · CRP {p.crp}</p><div className="mt-4 flex flex-wrap gap-2">{p.specialties.map(s=><span key={s} className="rounded-full bg-white px-3 py-1.5 text-xs shadow-sm">{s}</span>)}</div><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4"><div><p className="flex items-center gap-1 text-lg font-semibold"><Star className="fill-amber-400 text-amber-400" size={18}/>{p.rating||'Novo'}</p><small className="text-sage-500">{p.reviews} avaliações</small></div><div><p className="flex items-center gap-1 text-lg font-semibold"><Users size={18}/>{p.sessions}</p><small className="text-sage-500">atendimentos</small></div><div><p className="text-lg font-semibold">{p.experience} anos</p><small className="text-sage-500">de experiência</small></div><div><p className="text-lg font-semibold">R$ {p.price}</p><small className="text-sage-500">por sessão</small></div></div><div className="mt-7 flex flex-wrap gap-3"><Button onClick={()=>navigate(`/cliente/agendar/${p.id}`)}>Agendar consulta</Button><Button variant="outline"><Heart size={17}/>Salvar</Button><Button variant="ghost"><MessageCircle size={17}/>Conversar</Button></div></div></section>
    <section className="mt-9 grid gap-5 lg:grid-cols-2"><Card className="p-6"><h2 className="text-lg font-semibold">Sobre mim</h2><p className="mt-3 text-sm leading-7 text-sage-600">{p.bio||'Este profissional ainda não adicionou uma biografia.'}</p></Card><Card className="p-6"><h2 className="text-lg font-semibold">Como posso ajudar?</h2><div className="mt-4 grid grid-cols-2 gap-3">{p.specialties.map(x=><span className="flex items-center gap-2 text-sm" key={x}><Check size={15} className="text-sage-600"/>{x}</span>)}</div></Card>
      <Card className="p-6"><div className="flex items-center justify-between"><h2 className="font-semibold">Avaliações</h2>{p.reviews>0&&<span className="text-xs text-sage-500">{p.reviews} avaliações</span>}</div>{p.testimonials.length?<div className="mt-4 grid gap-4 sm:grid-cols-2">{p.testimonials.slice(0,2).map((text,index)=><div key={`${text}-${index}`} className="rounded-2xl bg-sage-50 p-4"><p className="text-amber-400">★★★★★</p><p className="mt-2 text-sm">“{text}”</p></div>)}</div>:<p className="mt-5 text-sm text-sage-500">Este profissional ainda não recebeu avaliações.</p>}</Card><Card className="p-6"><h2 className="flex items-center gap-2 font-semibold"><CalendarDays size={18}/>Próximos horários disponíveis</h2><div className="mt-5 grid grid-cols-3 gap-2">{[['Ter','14/07','14:00'],['Qua','15/07','17:00'],['Qui','16/07','20:00']].map(x=><button key={x[0]} className="rounded-2xl border border-sage-200 p-3 text-center hover:bg-sage-50"><strong className="block text-sm">{x[0]}</strong><small>{x[1]}</small><span className="mt-1 flex items-center justify-center gap-1 text-xs text-sage-600"><Clock size={12}/>{x[2]}</span></button>)}</div><Button full className="mt-5" onClick={()=>navigate(`/cliente/agendar/${p.id}`)}>Ver agenda completa</Button></Card></section>
  </div>
}
